name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
